# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/storage/custom_flash_driver:

examples/storage/emmc:
  enable:
    - if: IDF_TARGET == "esp32s3"
      reason: only support on esp32s3

examples/storage/ext_flash_fatfs:
  disable:
    - if: IDF_TARGET == "esp32p4"
      reason: not supported yet
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32s2"]
      temporary: true
      reason: lack of runners

examples/storage/fatfsgen:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only one target needed

examples/storage/nvs_rw_blob:

examples/storage/nvs_rw_value:

examples/storage/nvs_rw_value_cxx:

examples/storage/nvsgen:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only one target needed

examples/storage/partition_api/partition_find:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      reason: only one target per arch needed

examples/storage/partition_api/partition_mmap:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      reason: only one target per arch needed

examples/storage/partition_api/partition_ops:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      reason: only one target per arch needed

examples/storage/parttool:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only one target needed

examples/storage/perf_benchmark:
  disable:
    - if: IDF_TARGET == "esp32p4" and CONFIG_NAME in ["sdmmc_1line", "sdmmc_4line", "sdspi_1line"]
      temporary: true
      reason: SDMMC and SDSPI not supported on P4 yet # TODO: IDF-6502, IDF-7501
  disable_test:
    - if: IDF_TARGET == "esp32p4" and CONFIG_NAME in ["spiflash"]
      temporary: true
      reason: SPIFLASH not supported on P4 yet, only build stage enabled # TODO: IDF-7499

examples/storage/sd_card/sdmmc:
  disable:
    - if: SOC_SDMMC_HOST_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET not in ["esp32"]
      temporary: true
      reason: lack of runners

examples/storage/sd_card/sdspi:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3", "esp32s2"]
      temporary: true
      reason: lack of runners

examples/storage/semihost_vfs:
  disable_test:
    - if: IDF_TARGET not in ["esp32"]
      temporary: true
      reason: lack of runners

examples/storage/spiffs:

examples/storage/spiffsgen:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only one target needed

examples/storage/wear_levelling:
