name: DangerJS Pull Request review

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  danger-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/dangerjs
    steps:
    - name: Check out PR head
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup NodeJS environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: .github/dangerjs/package-lock.json

    - name: Install DangerJS dependencies
      run: npm install

    - name: Run DangerJS
      run: npx danger ci --failOnErrors -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
